spring:
  profiles:
    active: dev


---
server: 
  port: 8201
#spring
spring:
  profiles: dev
  application:
    name: springcloud-provider-dept-dev

#Eureka
eureka:
  client:
    service-url:
      defaultZone: http://Eureka7001.com:7001/eureka/dev
      

---
server: 
  port: 8202
#spring
spring:
  profiles: test
  application:
    name: springcloud-provider-dept-test

#Eureka
eureka:
  client:
    service-url:
      defaultZone: http://Eureka7001.com:7001/eureka/test
