server:
  port: 7001

spring:
  profiles: eureka7001

#Eureka
eureka:
  instance:
    hostname: Eureka7001.com #Eureka服务端的实例名称
  client:
    register-with-eureka: false #表示是否向eureka注册中心注册自己
    fetch-registry: false #为false，表示自己为注册中心
    service-url:  #监控页面
      defaultZone: http://Eureka7002.com:7002/eureka/,http://Eureka7003.com:7003/eureka/


---
server:
  port: 7002

spring:
  profiles: eureka7002

#Eureka
eureka:
  instance:
    hostname: Eureka7002.com #Eureka服务端的实例名称
  client:
    register-with-eureka: false #表示是否向eureka注册中心注册自己
    fetch-registry: false #为false，表示自己为注册中心
    service-url:  #监控页面
      defaultZone: http://Eureka7001.com:7001/eureka/,http://Eureka7003.com:7003/eureka/



---
server:
  port: 7003
  
spring:
  profiles: eureka7003


#Eureka
eureka:
  instance:
    hostname: Eureka7003.com #Eureka服务端的实例名称
  client:
    register-with-eureka: false #表示是否向eureka注册中心注册自己
    fetch-registry: false #为false，表示自己为注册中心
    service-url:  #监控页面
      defaultZone: http://Eureka7001.com:7001/eureka/,http://Eureka7002.com:7002/eureka/































